### ISSUE TITLE
Variable overrider

### ISSUE THREAD

**Issue by admk** [Aaron-Zhao123/mayo-dev#10]
A work-in-progress variable overrider is now in branch `feature/surgery`.

**Comment by admk** [comment]
ce2f362 implements a working variable overrider.

To run the demo, simply use:
```
$ ./my train models/lenet5_quantized.yaml <your favourite dataset> <your favourite trainer>
```
As shown in the `lenet5_quantized.yaml` example, all you need to do is to define weights and biases overriders to override these variables:
```yaml
weights_overrider: &overrider
  type: mayo.surgery.fixed_point_quantizer
  integer_width: 1
  fractional_width: 4
biases_overrider: *overrider
```

Additionally, using `system.log_level.mayo=debug` prints variable overriding related debug messages in addition to other debug infos.

Activation overriding to follow in a separate commit.
