### ISSUE TITLE
Activation overrider

### ISSUE THREAD

**Issue by admk** [Aaron-Zhao123/mayo-dev#11]
Activation overriding would be implemented by a custom activation function. Such custom activation can be written in YAML as follows for each layer instantiation:
```yaml
activation_fn:
  - type: mayo.surgery.fixed_point_quantizer
    integer_width: 1
    fractional_width: 4
  - type: tensorflow.nn.relu
```

Here, instead of a single hyperobject, we could supply a list of hyperobjects to be instantiated, and their corresponding action would be composed in sequence.

As an example, the above instantiation of the activation function would result in an activation function object which first quantizes pre-activation results, then apply a ReLU activation on them.

Such composition can be reused in other places such as `(weights|biases)_(initializer|regularizer)`, `preprocess` stages, and etc.

**Comment by admk** [comment]
`tensorflow.nn.relu` is not an object. We should consider adding `activation_overrider` to supported params of net instantiation.

**Comment by admk** [comment]
`lenet_makaizou.yaml` show an example of the newly implemented activation overrider in e1e5f7f.
```yaml
activation_overrider:
  type: mayo.override.FixedPointQuantizer
  integer_width: 1
  fractional_width: 4
```
