### ISSUE TITLE
Overrider composition

### ISSUE THREAD

**Issue by admk** [Aaron-Zhao123/mayo-dev#14]
Certain places requires custom chain-able hyperobjects written in YAML as follows as seen in #11:
```yaml
activation_fn:
  - type: mayo.surgery.fixed_point_quantizer
    integer_width: 1
    fractional_width: 4
  - type: tensorflow.nn.relu
```
Here, instead of a single hyperobject, we could supply a list of hyperobjects to be instantiated, and their corresponding action would be composed in sequence.

Other examples could be chaining parameters pruning with quantization, and composing preprocessing actions.

**Comment by admk** [comment]
`lenet5_makaizou.yaml` has a working example of overrider composition:
```yaml
weights_overrider: &overrider
  - type: mayo.override.MeanStdPruner
    alpha: 0.1
  - type: mayo.override.FixedPointQuantizer
    integer_width: 1
    fractional_width: 4
```
