### ISSUE TITLE
Snapshot network when test acc is large

### ISSUE THREAD

**Issue by Aaron-Zhao123** [Aaron-Zhao123/mayo-dev#17]
Test accuracy fluctuates during fine-tuning.

Consider support the following feature:
```
if (test_acc > stored_test_acc)
    store checkpoint
    stored_test_acc = test_acc
```

This might be helpful in finding a better local minimum during training.

**Comment by admk** [comment]
We need a way to prevent too many checkpoints being generated because when the condition is satisfied for many consecutive iterations.

Perhaps we could add this below in `mayo/system.yaml`?
```yaml
system:
  checkpoint:
    save:
      accuracy: (accuracy)
      interval:
        - (minimum number of steps that must elapse between consecutive saves)
        - (and the maximum)
```

Please use a separate `feature/` branch for this feature as it breaks the way the current YAML is written.
