### ISSUE TITLE
给网络添加default input shape，确保网络结构 dataset-agnostic

### ISSUE THREAD

**Issue by admk** [Aaron-Zhao123/mayo-dev#6]
改动原因
---
目前网络结构会随着dataset大小而改变，导致无法在mobilenets或alexnet之类的大网络上使用mnist，flowers或cifar10。

实现方式
---
preprocessing会负责使用上面的shape定义，自动resize最后的图片，并且保证channel数为预期。如`dataset.shape.channels = 3` 而 `input.channel = 1` 我们自动将rgb图片转换为greyscale，如反过来则自动重复三次同一个灰度channel。

YAML改动
---
方式为 model yaml 中添加：
```yaml
dataset:
  preprocessed_shape:
    height: 32
    width: 32
    channels: 3
```
